############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Mi Historia"
url = "/about"
weight = 2



[[main]]
name = "Blog"
url = "/blog"


[[main]]
name = "Trail Running"
url = "/trail-running"


[[main]]

name = "Contacto"
url = "/contact"    



# footer menu
[[footer]]
name = "Contacto"
url = "/contact"
weight = 1

[[footer]]
name = "Politíca de privacidad"
url = "/privacy-policy"
weight = 3
